version: '3'

services:
  js:
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./docker-cache/npm:/root/.npm
      - ./client:/var/www/html
    working_dir: /var/www/html
    entrypoint: npm start

  php:
    build: ./server
    ports:
      - "8080:80"
    links:
      - db
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./server/public:/var/www/html

  db:
    image: mariadb:10.2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: plokijuh
      MYSQL_USER: dev
      MYSQL_PASSWORD: plokijuh
      MYSQL_DATABASE: hiring
